version: "2.1"
services:
  db:
    build: ./postgres
    restart: "unless-stopped"
  bot:
    build: .
    restart: "unless-stopped"
    environment:
      TG_API_KEY:  # API key of the bot
      SENTRY_DSN: # https://...
